name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.16
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '16'
      - name: Build with Maven
        run: mvn -B -e -U clean package
      - uses: actions/upload-artifact@v3
        with:
          name: WheelCore
          path: target/WheelCore-1.0-SNAPSHOT.jar
